#!/usr/bin/env node
/* Bundles data/*.json into dist/msfix-data.js and copies the userscript into dist/. */
const fs = require('fs');
const path = require('path');

const root = __dirname;
const read = (p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));

const i18nPatch = read('data/i18n-patch.json');
const dict = read('data/dictionary.json');
const rules = read('data/rules.json');
const css = fs.readFileSync(path.join(root, 'data/ui-fixes.css'), 'utf8');

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });

const payload = { i18nPatch, dict, rules, css };
const js = '/* Generated by build.js — do not edit. Data for MapleScouter English Fix. */\n' +
  'window.__MSFIX_DATA__ = ' + JSON.stringify(payload) + ';\n';
fs.writeFileSync(path.join(root, 'dist/msfix-data.js'), js);

// Tampermonkey caches @require payloads by URL and never refetches an unchanged one, so a
// data-only release (new translations, same script) would never reach anyone who already had
// the script installed — their 3MB payload stays frozen at whatever version they first got.
// Stamp the version into the URL so every release pulls a fresh payload. Derived from
// @version here so the two can't drift.
const userSrc = fs.readFileSync(path.join(root, 'src/maplescouter-en-fix.user.js'), 'utf8');
const version = (userSrc.match(/@version\s+([\d.]+)/) || [])[1];
if (!version) throw new Error('no @version in userscript');
const stamped = userSrc.replace(
  /(@require\s+\S*?\/dist\/msfix-data\.js)(\?v=[\d.]+)?/,
  '$1?v=' + version
);
if (stamped.indexOf('msfix-data.js?v=' + version) === -1) throw new Error('failed to stamp @require URL');
fs.writeFileSync(path.join(root, 'dist/maplescouter-en-fix.user.js'), stamped);

console.log('dist/msfix-data.js:', (fs.statSync(path.join(root, 'dist/msfix-data.js')).size / 1024 / 1024).toFixed(2) + ' MB');
console.log('userscript:', 'v' + version, '| @require stamped ?v=' + version);
console.log('i18nPatch keys:', Object.keys(i18nPatch).length, '| dict entries:', Object.keys(dict).length, '| rules:', rules.length);
